project_id = "uhlkuofwittcveeyyjzz"

[functions.groq-chat]
verify_jwt = false

[functions.ai-moderation]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.inworld-realtime]
verify_jwt = false

[functions.activate-role]
verify_jwt = true

[functions.admin-set-role]
verify_jwt = true
[functions.message-guard]
verify_jwt = true
